apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: smartshield
type: Opaque
stringData:
  redis-url: "redis://redis.smartshield.svc.cluster.local:6379"
  elasticsearch-url: "http://elasticsearch.smartshield.svc.cluster.local:9200"
  tls-cert: "your-tls-certificate-here" # Replace with actual cert in production
  tls-key: "your-tls-private-key-here" # Replace with actual key in production
