server:
  port: 8080
  tls:
    enabled: true
    cert_path: /app/certs/tls.crt
    key_path: /app/certs/tls.key
redis:
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
elasticsearch:
  max_retries: 3
  timeout: 10s
detection:
  yara_rules_path: /app/rules
  scan_timeout: 5s
  max_concurrent_scans: 10
  ml:
    enabled: true
    model_path: /app/models/cnn_bilstm
    input_size: 128
    hidden_size: 64
    num_layers: 2
    dropout_rate: 0.2
    learning_rate: 0.001
    batch_size: 32
    epochs: 10
    min_accuracy: 0.85
    max_false_positive: 0.15
    max_false_negative: 0.15
    update_interval: 1h
    retrain_interval: 24h
security:
  rate_limit: 1000
  rate_limit_burst: 2000
  max_request_size: 10485760 # 10MB
