apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: smartshield
  labels:
    app: smartshield-agent
data:
  config.yaml: |
    agent_id: ${AGENT_ID}
    backend:
      url: ${BACKEND_URL}
      timeout: 10s
    tls:
      insecure_skip_verify: false
    security:
      enable_payload_encryption: true
      rate_limit: 100
      rate_limit_burst: 200
      encryption_key: ${ENCRYPTION_KEY}
    monitoring:
      metrics_interval: 30s
      health_check_interval: 60s
      health_check_port: 8081
    network:
      interface: eth0
      bpf_filter: ""
    system:
      log_paths:
        - /var/log/syslog
        - /var/log/auth.log
